export const teamNameNormalization = {
  'Korea Republic': 'South Korea',
  'Korea (South)': 'South Korea',
  'Korea  Republic': 'South Korea',
  'Republic of Korea': 'South Korea',
  'Iran, Islamic Republic of': 'Iran',
  'Iran (Islamic Republic of)': 'Iran',
  'United States of America': 'United States',
  'USA': 'United States',
  'United States ': 'United States',
  'England ': 'England',
  'Brazil ': 'Brazil',
  'France ': 'France',
  'Germany ': 'Germany',
  'Spain ': 'Spain',
  'Portugal ': 'Portugal',
  'Argentina ': 'Argentina',
  'Netherlands': 'Netherlands',
  'Netherlands ': 'Netherlands',
  'Croatia ': 'Croatia',
  'Morocco ': 'Morocco',
  'Japan ': 'Japan',
  'Belgium ': 'Belgium',
  'Switzerland ': 'Switzerland',
  'Serbia ': 'Serbia',
  'Cameroon ': 'Cameroon',
  'Mexico ': 'Mexico',
  'Poland ': 'Poland',
  'Saudi Arabia': 'Saudi Arabia',
  'Saudi Arabia ': 'Saudi Arabia',
  'Denmark ': 'Denmark',
  'Tunisia ': 'Tunisia',
  'Australia ': 'Australia',
  'Wales ': 'Wales',
  'Senegal ': 'Senegal',
  'Ecuador ': 'Ecuador',
  'Qatar ': 'Qatar',
  'Canada ': 'Canada',
  'Costa Rica': 'Costa Rica',
  'Costa Rica ': 'Costa Rica',
  'Germany (FRG)': 'Germany',
  'West Germany': 'Germany',
  'Soviet Union': 'Soviet Union',
  'Czechoslovakia': 'Czechoslovakia',
  'Yugoslavia': 'Yugoslavia',
  'Serbia and Montenegro': 'Serbia and Montenegro',
  'Zaire': 'DR Congo',
  'DR Congo': 'DR Congo',
  'Ivory Coast': 'Côte d\'Ivoire',
  'Cote dIvoire': 'Côte d\'Ivoire',
  'Côte dIvoire': 'Côte d\'Ivoire',
  'Trinidad & Tobago': 'Trinidad and Tobago',
  'Trinidad and Tobago': 'Trinidad and Tobago',
  'United Arab Emirates': 'UAE',
  'UAE': 'UAE',
  'New Zealand ': 'New Zealand',
  'Norway ': 'Norway',
  'Sweden ': 'Sweden',
  'Austria ': 'Austria',
  'Hungary ': 'Hungary',
  'Italy ': 'Italy',
  'Romania ': 'Romania',
  'Bulgaria ': 'Bulgaria',
  'Greece ': 'Greece',
  'Turkey ': 'Turkey',
  'Russia ': 'Russia',
  'Ukraine ': 'Ukraine',
  'Slovakia ': 'Slovakia',
  'Slovenia ': 'Slovenia',
  'Bosnia and Herzegovina': 'Bosnia and Herzegovina',
  'Bosnia Herzegovina': 'Bosnia and Herzegovina',
  'Republic of Ireland': 'Ireland',
  'Northern Ireland': 'Northern Ireland',
  'Scotland ': 'Scotland',
  'Wales': 'Wales',
  'Algeria ': 'Algeria',
  'Egypt ': 'Egypt',
  'Nigeria ': 'Nigeria',
  'Ghana ': 'Ghana',
  'South Africa': 'South Africa',
  'South Africa ': 'South Africa',
  'Togo ': 'Togo',
  'Angola ': 'Angola',
  'Zambia ': 'Zambia',
  'Malawi ': 'Malawi',
  'Mozambique ': 'Mozambique',
  'Ivory Coast': 'Côte d\'Ivoire',
  'Burkina Faso': 'Burkina Faso',
  'Mali ': 'Mali',
  'Guinea ': 'Guinea',
  'Kenya ': 'Kenya',
  'Ethiopia ': 'Ethiopia',
  'Morocco': 'Morocco',
  'Tunisia': 'Tunisia',
  'Algeria': 'Algeria',
  'Libya ': 'Libya',
  'Sudan ': 'Sudan',
  'Egypt': 'Egypt',
  'Nigeria': 'Nigeria',
  'Cameroon': 'Cameroon',
  'Ghana': 'Ghana',
  'Ivory Coast ': 'Côte d\'Ivoire',
  'Senegal': 'Senegal',
  'Togo': 'Togo',
  'Benin ': 'Benin',
  'Mali': 'Mali',
  'Burkina Faso ': 'Burkina Faso',
  'Guinea': 'Guinea',
  'Congo': 'Congo',
  'Congo DR': 'DR Congo',
  'Czechia': 'Czech Republic',
  'Curacao': 'Curaçao',
  'Cabo Verde': 'Cape Verde',
  'Bosnia': 'Bosnia and Herzegovina',
  'Zambia': 'Zambia',
  'Angola': 'Angola',
  'South Africa ': 'South Africa',
  'Namibia ': 'Namibia',
  'Zimbabwe ': 'Zimbabwe',
  'Botswana ': 'Botswana',
  'Swaziland': 'Eswatini',
  'Eswatini': 'Eswatini',
  'Lesotho ': 'Lesotho',
  'Madagascar ': 'Madagascar',
  'Mauritius ': 'Mauritius',
  'Seychelles ': 'Seychelles',
  'Comoros ': 'Comoros',
  'São Tomé and Príncipe': 'Sao Tome and Principe',
  'Equatorial Guinea': 'Equatorial Guinea',
  'Gabon ': 'Gabon',
  'Chad ': 'Chad',
  'Central African Republic': 'Central African Republic',
  'Sierra Leone': 'Sierra Leone',
  'Liberia ': 'Liberia',
  'Guinea-Bissau': 'Guinea-Bissau',
  'Cape Verde': 'Cape Verde',
  'Gambia': 'Gambia',
  'Senegal ': 'Senegal',
  'Mauritania ': 'Mauritania',
  'Niger ': 'Niger',
  'Chad': 'Chad',
  'Sudan': 'Sudan',
  'Eritrea ': 'Eritrea',
  'Djibouti ': 'Djibouti',
  'Somalia ': 'Somalia',
  'Kenya': 'Kenya',
  'Uganda ': 'Uganda',
  'Tanzania ': 'Tanzania',
  'Rwanda ': 'Rwanda',
  'Burundi ': 'Burundi',
  'Malawi': 'Malawi',
  'Zambia ': 'Zambia',
  'Mozambique': 'Mozambique',
  'Madagascar': 'Madagascar',
  'India ': 'India',
  'Pakistan ': 'Pakistan',
  'Bangladesh ': 'Bangladesh',
  'Sri Lanka ': 'Sri Lanka',
  'Nepal ': 'Nepal',
  'Bhutan ': 'Bhutan',
  'Maldives ': 'Maldives',
  'Afghanistan ': 'Afghanistan',
  'Iran': 'Iran',
  'Iraq ': 'Iraq',
  'Syria ': 'Syria',
  'Lebanon ': 'Lebanon',
  'Jordan ': 'Jordan',
  'Palestine ': 'Palestine',
  'Israel ': 'Israel',
  'Saudi Arabia ': 'Saudi Arabia',
  'Yemen ': 'Yemen',
  'Oman ': 'Oman',
  'UAE ': 'UAE',
  'Qatar': 'Qatar',
  'Bahrain ': 'Bahrain',
  'Kuwait ': 'Kuwait',
  'Turkey': 'Turkey',
  'Cyprus ': 'Cyprus',
  'Armenia ': 'Armenia',
  'Azerbaijan ': 'Azerbaijan',
  'Georgia ': 'Georgia',
  'Kazakhstan ': 'Kazakhstan',
  'Uzbekistan ': 'Uzbekistan',
  'Turkmenistan ': 'Turkmenistan',
  'Tajikistan ': 'Tajikistan',
  'Kyrgyzstan ': 'Kyrgyzstan',
  'Mongolia ': 'Mongolia',
  'China': 'China',
  'Japan': 'Japan',
  'South Korea': 'South Korea',
  'North Korea': 'North Korea',
  'Indonesia ': 'Indonesia',
  'Malaysia ': 'Malaysia',
  'Singapore ': 'Singapore',
  'Thailand ': 'Thailand',
  'Vietnam ': 'Vietnam',
  'Cambodia ': 'Cambodia',
  'Laos ': 'Laos',
  'Myanmar ': 'Myanmar',
  'Philippines ': 'Philippines',
  'Brunei ': 'Brunei',
  'East Timor': 'Timor-Leste',
  'Timor-Leste': 'Timor-Leste',
  'Australia': 'Australia',
  'New Zealand': 'New Zealand',
  'Fiji ': 'Fiji',
  'Papua New Guinea': 'Papua New Guinea',
  'Solomon Islands': 'Solomon Islands',
  'Vanuatu ': 'Vanuatu',
  'New Caledonia': 'New Caledonia',
  'Tonga ': 'Tonga',
  'Samoa ': 'Samoa',
  'American Samoa': 'American Samoa',
  'Cook Islands': 'Cook Islands',
  'Niue ': 'Niue',
  'Norfolk Island': 'Norfolk Island',
  'France': 'France',
  'Germany': 'Germany',
  'Italy': 'Italy',
  'Spain': 'Spain',
  'Portugal': 'Portugal',
  'United Kingdom': 'United Kingdom',
  'England': 'England',
  'Scotland': 'Scotland',
  'Northern Ireland': 'Northern Ireland',
  'Wales ': 'Wales',
  'Ireland': 'Ireland',
  'Iceland ': 'Iceland',
  'Norway': 'Norway',
  'Sweden': 'Sweden',
  'Finland ': 'Finland',
  'Denmark': 'Denmark',
  'Belgium': 'Belgium',
  'Netherlands ': 'Netherlands',
  'Luxembourg ': 'Luxembourg',
  'Switzerland': 'Switzerland',
  'Austria': 'Austria',
  'Hungary': 'Hungary',
  'Czech Republic': 'Czech Republic',
  'Slovakia': 'Slovakia',
  'Slovenia': 'Slovenia',
  'Croatia': 'Croatia',
  'Bosnia Herzegovina ': 'Bosnia Herzegovina',
  'Serbia': 'Serbia',
  'Montenegro ': 'Montenegro',
  'North Macedonia': 'North Macedonia',
  'Albania ': 'Albania',
  'Greece': 'Greece',
  'Bulgaria': 'Bulgaria',
  'Romania': 'Romania',
  'Moldova ': 'Moldova',
  'Ukraine': 'Ukraine',
  'Belarus ': 'Belarus',
  'Russia': 'Russia',
  'Estonia ': 'Estonia',
  'Latvia ': 'Latvia',
  'Lithuania ': 'Lithuania',
  'Poland': 'Poland',
  'Czechoslovakia ': 'Czechoslovakia',
  'Yugoslavia ': 'Yugoslavia',
  'Serbia and Montenegro ': 'Serbia and Montenegro',
  'Soviet Union ': 'Soviet Union',
  'United States': 'United States',
  'Canada': 'Canada',
  'Mexico': 'Mexico',
  'Costa Rica': 'Costa Rica',
  'Honduras ': 'Honduras',
  'Guatemala ': 'Guatemala',
  'El Salvador': 'El Salvador',
  'Nicaragua ': 'Nicaragua',
  'Panama ': 'Panama',
  'Cuba ': 'Cuba',
  'Jamaica ': 'Jamaica',
  'Haiti ': 'Haiti',
  'Dominican Republic': 'Dominican Republic',
  'Trinidad and Tobago ': 'Trinidad and Tobago',
  'Barbados ': 'Barbados',
  'Grenada ': 'Grenada',
  'Antigua and Barbuda': 'Antigua and Barbuda',
  'Saint Kitts and Nevis': 'Saint Kitts and Nevis',
  'Saint Lucia': 'Saint Lucia',
  'Saint Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
  'Dominica ': 'Dominica',
  'Aruba ': 'Aruba',
  'Netherlands Antilles': 'Netherlands Antilles',
  'Anguilla ': 'Anguilla',
  'Bermuda ': 'Bermuda',
  'British Virgin Islands': 'British Virgin Islands',
  'Cayman Islands': 'Cayman Islands',
  'Turks and Caicos Islands': 'Turks and Caicos Islands',
  'Montserrat ': 'Montserrat',
  'Argentina': 'Argentina',
  'Brazil': 'Brazil',
  'Uruguay': 'Uruguay',
  'Paraguay ': 'Paraguay',
  'Chile ': 'Chile',
  'Peru ': 'Peru',
  'Bolivia ': 'Bolivia',
  'Ecuador': 'Ecuador',
  'Colombia ': 'Colombia',
  'Venezuela ': 'Venezuela',
  'Guyana ': 'Guyana',
  'Suriname ': 'Suriname',
  'French Guiana': 'French Guiana',
  'Falkland Islands': 'Falkland Islands',
  'South Georgia and the South Sandwich Islands': 'South Georgia and the South Sandwich Islands'
};

export const teamNameChineseMapping = {
  'South Korea': '韩国',
  'German DR': '东德',
  'North Korea': '朝鲜',
  'Iran': '伊朗',
  'United States': '美国',
  'England': '英格兰',
  'Brazil': '巴西',
  'France': '法国',
  'Germany': '德国',
  'Spain': '西班牙',
  'Portugal': '葡萄牙',
  'Argentina': '阿根廷',
  'Netherlands': '荷兰',
  'Croatia': '克罗地亚',
  'Morocco': '摩洛哥',
  'Japan': '日本',
  'Belgium': '比利时',
  'Switzerland': '瑞士',
  'Serbia': '塞尔维亚',
  'Cameroon': '喀麦隆',
  'Mexico': '墨西哥',
  'Poland': '波兰',
  'Saudi Arabia': '沙特阿拉伯',
  'Denmark': '丹麦',
  'Tunisia': '突尼斯',
  'Australia': '澳大利亚',
  'Wales': '威尔士',
  'Senegal': '塞内加尔',
  'Ecuador': '厄瓜多尔',
  'Qatar': '卡塔尔',
  'Canada': '加拿大',
  'Costa Rica': '哥斯达黎加',
  'Germany (FRG)': '德国',
  'West Germany': '西德',
  'Soviet Union': '苏联',
  'Czechoslovakia': '捷克斯洛伐克',
  'Yugoslavia': '南斯拉夫',
  'Serbia and Montenegro': '塞尔维亚和黑山',
  'Zaire': '扎伊尔',
  'DR Congo': '刚果民主共和国',
  "Côte d'Ivoire": '科特迪瓦',
  'Trinidad and Tobago': '特立尼达和多巴哥',
  'UAE': '阿联酋',
  'New Zealand': '新西兰',
  'Norway': '挪威',
  'Sweden': '瑞典',
  'Austria': '奥地利',
  'Hungary': '匈牙利',
  'Italy': '意大利',
  'Romania': '罗马尼亚',
  'Bulgaria': '保加利亚',
  'Greece': '希腊',
  'Turkey': '土耳其',
  'Russia': '俄罗斯',
  'Ukraine': '乌克兰',
  'Slovakia': '斯洛伐克',
  'Slovenia': '斯洛文尼亚',
  'Bosnia Herzegovina': '波斯尼亚和黑塞哥维那',
  'Ireland': '爱尔兰',
  'Northern Ireland': '北爱尔兰',
  'Scotland': '苏格兰',
  'Algeria': '阿尔及利亚',
  'Egypt': '埃及',
  'Nigeria': '尼日利亚',
  'Ghana': '加纳',
  'South Africa': '南非',
  'Togo': '多哥',
  'Angola': '安哥拉',
  'Zambia': '赞比亚',
  'Malawi': '马拉维',
  'Mozambique': '莫桑比克',
  'Burkina Faso': '布基纳法索',
  'Mali': '马里',
  'Guinea': '几内亚',
  'Kenya': '肯尼亚',
  'Ethiopia': '埃塞俄比亚',
  'Libya': '利比亚',
  'Sudan': '苏丹',
  'Benin': '贝宁',
  'Congo': '刚果',
  'Namibia': '纳米比亚',
  'Zimbabwe': '津巴布韦',
  'Botswana': '博茨瓦纳',
  'Eswatini': '斯威士兰',
  'Lesotho': '莱索托',
  'Madagascar': '马达加斯加',
  'Mauritius': '毛里求斯',
  'Seychelles': '塞舌尔',
  'Comoros': '科摩罗',
  'Sao Tome and Principe': '圣多美和普林西比',
  'Equatorial Guinea': '赤道几内亚',
  'Gabon': '加蓬',
  'Chad': '乍得',
  'Central African Republic': '中非共和国',
  'Sierra Leone': '塞拉利昂',
  'Liberia': '利比里亚',
  'Guinea-Bissau': '几内亚比绍',
  'Cape Verde': '佛得角',
  'Curaçao': '库拉索',
  'Bosnia and Herzegovina': '波黑',
  'DR Congo': '民主刚果',
  'Gambia': '冈比亚',
  'Mauritania': '毛里塔尼亚',
  'Niger': '尼日尔',
  'Eritrea': '厄立特里亚',
  'Djibouti': '吉布提',
  'Somalia': '索马里',
  'Uganda': '乌干达',
  'Tanzania': '坦桑尼亚',
  'Rwanda': '卢旺达',
  'Burundi': '布隆迪',
  'India': '印度',
  'Pakistan': '巴基斯坦',
  'Bangladesh': '孟加拉国',
  'Sri Lanka': '斯里兰卡',
  'Nepal': '尼泊尔',
  'Bhutan': '不丹',
  'Maldives': '马尔代夫',
  'Afghanistan': '阿富汗',
  'Iraq': '伊拉克',
  'Syria': '叙利亚',
  'Lebanon': '黎巴嫩',
  'Jordan': '约旦',
  'Palestine': '巴勒斯坦',
  'Israel': '以色列',
  'Yemen': '也门',
  'Oman': '阿曼',
  'Bahrain': '巴林',
  'Kuwait': '科威特',
  'Cyprus': '塞浦路斯',
  'Armenia': '亚美尼亚',
  'Azerbaijan': '阿塞拜疆',
  'Georgia': '格鲁吉亚',
  'Kazakhstan': '哈萨克斯坦',
  'Uzbekistan': '乌兹别克斯坦',
  'Turkmenistan': '土库曼斯坦',
  'Tajikistan': '塔吉克斯坦',
  'Kyrgyzstan': '吉尔吉斯斯坦',
  'Mongolia': '蒙古',
  'China': '中国',
  'Indonesia': '印度尼西亚',
  'Malaysia': '马来西亚',
  'Singapore': '新加坡',
  'Thailand': '泰国',
  'Vietnam': '越南',
  'Cambodia': '柬埔寨',
  'Laos': '老挝',
  'Myanmar': '缅甸',
  'Philippines': '菲律宾',
  'Brunei': '文莱',
  'Timor-Leste': '东帝汶',
  'Fiji': '斐济',
  'Papua New Guinea': '巴布亚新几内亚',
  'Solomon Islands': '所罗门群岛',
  'Vanuatu': '瓦努阿图',
  'New Caledonia': '新喀里多尼亚',
  'Tonga': '汤加',
  'Samoa': '萨摩亚',
  'American Samoa': '美属萨摩亚',
  'Cook Islands': '库克群岛',
  'Niue': '纽埃',
  'Norfolk Island': '诺福克岛',
  'United Kingdom': '英国',
  'Iceland': '冰岛',
  'Finland': '芬兰',
  'Luxembourg': '卢森堡',
  'Czech Republic': '捷克共和国',
  'North Macedonia': '北马其顿',
  'Albania': '阿尔巴尼亚',
  'Moldova': '摩尔多瓦',
  'Belarus': '白俄罗斯',
  'Estonia': '爱沙尼亚',
  'Latvia': '拉脱维亚',
  'Lithuania': '立陶宛',
  'Honduras': '洪都拉斯',
  'Guatemala': '危地马拉',
  'El Salvador': '萨尔瓦多',
  'Nicaragua': '尼加拉瓜',
  'Panama': '巴拿马',
  'Cuba': '古巴',
  'Jamaica': '牙买加',
  'Haiti': '海地',
  'Dominican Republic': '多米尼加共和国',
  'Barbados': '巴巴多斯',
  'Grenada': '格林纳达',
  'Antigua and Barbuda': '安提瓜和巴布达',
  'Saint Kitts and Nevis': '圣基茨和尼维斯',
  'Saint Lucia': '圣卢西亚',
  'Saint Vincent and the Grenadines': '圣文森特和格林纳丁斯',
  'Dominica': '多米尼克',
  'Aruba': '阿鲁巴',
  'Netherlands Antilles': '荷属安的列斯',
  'Anguilla': '安圭拉',
  'Bermuda': '百慕大',
  'British Virgin Islands': '英属维尔京群岛',
  'Cayman Islands': '开曼群岛',
  'Turks and Caicos Islands': '特克斯和凯科斯群岛',
  'Montserrat': '蒙特塞拉特',
  'Paraguay': '巴拉圭',
  'Chile': '智利',
  'Peru': '秘鲁',
  'Bolivia': '玻利维亚',
  'Colombia': '哥伦比亚',
  'Venezuela': '委内瑞拉',
  'Guyana': '圭亚那',
  'Suriname': '苏里南',
  'French Guiana': '法属圭亚那',
  'Falkland Islands': '福克兰群岛',
  'South Georgia and the South Sandwich Islands': '南乔治亚岛和南桑威奇群岛',
  'Uruguay': '乌拉圭'
};

export function normalizeTeamName(name) {
  if (!name || typeof name !== 'string') {
    return name;
  }
  const trimmed = name.trim();
  return teamNameNormalization[trimmed] || trimmed;
}

export function getChineseName(name) {
  if (!name || typeof name !== 'string') {
    return name;
  }
  const normalized = normalizeTeamName(name);
  return teamNameChineseMapping[normalized] || normalized;
}
